package cn.li.router.compiler.utils

import cn.li.router.compiler.data.AutowiredMeta
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger


/**
 * 生成 IAutowired 实现类
 * */
fun AutowiredMeta.genIAutowiredImpl(
    codeGenerator: CodeGenerator,
    logger: KSPLogger
) {
    val dependencies = Dependencies(true)
    val className = getGenerateClassFileName()
    codeGenerator.createNewFile(dependencies, Constants.GENERATE_PACKAGE_NAME, className, "kt")
        .bufferedWriter(Charsets.UTF_8)
        .use { writer ->
            writer.appendLine("package ${Constants.GENERATE_PACKAGE_NAME}")
            writer.appendLine()
            writer.appendLine("/* The file auto generated by LiRouter/Grimrise. Don't edit it! */")
            writer.appendLine("class $className: cn.li.router.api.generate.IAutowired {")
            writer.appendLine("\toverride fun autowired(target: Any?) {")
            writer.appendLine("\t\tval obj = (target as? ${ownerQualifiedName}) ?: return")

            items.forEachIndexed { idx, item ->
                writer.appendLine("\t\tval meta${idx} = ${item.toAutowiredMetaString()}")
                writer.appendLine("\t\tcn.li.router.runtime.AutowiredArgumentsParser.parse<${item.type}>(obj, meta${idx})?.let { obj.${item.fieldName} = it }")
            }
            writer.appendLine("\t}")
            writer.appendLine("}")
        }
    logger.info("[genIAutowiredImpl] file: $className.kt")
}